[package]
name = "michael_visualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.21.0"
eframe="*"
data_format = {path="../data_format"}
egui_extras = "0.21.0"
egui_dock = "0.6.0"
