name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Ubuntu XDG
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            flags: '--no-default-features --features xdg-portal'

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --target ${{ matrix.target }} ${{ matrix.flags }}
    - name: Test
      run: cargo test --target ${{ matrix.target }} ${{ matrix.flags }}